### ISSUE TITLE
Error opening Event Log

### ISSUE THREAD

**Issue by bmmojo** [keydet89/Events-Ripper#2]
Whenever I run the batch file, I will get an error:
```
PS C:\Users\testlab\Downloads\Events-Ripper-main> .\wevtx.bat C:\Users\testlab\Desktop\ripper\Microsoft-Windows-Bits-Client%4Operational.evtx C:\Users\testlab\Desktop\ripper\test1.txt
Cannot open <from-entity>: Error opening event log "\\?\C:\Users\testlab\Desktop\ripper\Microsoft-Windows-Bits-Client%4Operational.evtx": The parameter is incorrect.
```

I have tried this on command prompt and "as administrator". 
I have tried running the batch file to the specific evtx in the Windows\System32\winevt\logs.

Am I doing something wrong?

**Comment by keydet89** [comment]
Honestly, I don't know. I've never run the tool via PowerShell, and I don't have a copy of the .evtx file to verify...

**Comment by bmmojo** [comment]
Hey @keydet89, you can close this ticket. I figured out the issue.

The `.evtx` had an attribute of RA. I had to turn off the "Read-Only" attribute in the file. Now it works on both `cmd.exe` and `powershell.exe`.

**Comment by bmmojo** [comment]
Hey @keydet89, I figured out the issue. 

The `.evtx` had an attribute of RA. I had to turn off the "Read-Only" attribute in the file. Now it works on both `cmd.exe` and `powershell.exe`.
